export const images = {
  Google: require("../../assets/icons/google.png"),
  bgImage1: require("../../assets/icons/bgImage1.png"),
  bgImage2: require("../../assets/icons/bgImage2.png"),
  bgImage3: require("../../assets/icons/bgImage3.png"),
  bgImage4: require("../../assets/icons/bgImage4.png"),
  bgImage5: require("../../assets/icons/bgImage5.png"),
  bgImage6: require("../../assets/icons/bgImage6.png"),
  bgImage7: require("../../assets/icons/bgImage7.png"),
  signupImage: require("../../assets/icons/singupImage.png"),
  LeftArrow: require("../../assets/icons/left-arrow.png"),
  RightArrow: require("../../assets/icons/arrow-right.png"),
  FormImage: require("../../assets/icons/Group1.png"),
  subjectBG: require("../../assets/icons/subjectBG.png"),
  DashBoard: require("../../assets/icons/dashboard.png"),
  DashBoard1: require("../../assets/icons/dashboard1.png"),
  Feedback: require("../../assets/icons/chat.png"),
  LogOut: require("../../assets/icons/log-out.png"),
  ReportAnIssue: require("../../assets/icons/warning.png"),
  RequestFeature: require("../../assets/icons/request.png"),
  PrivacyPolicY: require("../../assets/icons/compliant.png"),
  Subject: require("../../assets/icons/subject.png"),
  Course: require("../../assets/icons/course.png"),
  About: require("../../assets/icons/about.png"),
};
